- hosts: "amazon-linux"
  remote_user: ec2-user
  vars:
    last_name: "Costin"
  become: yes
  tasks:
    - name: Install web-server and nodejs
      dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - httpd
        - nodejs

    - name: Start and enable autostart of web-server
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Status of web-server
      ansible.builtin.service:
        name: httpd
        state: reloaded

    - name: Create names.txt with content on Amazon Linux
      copy:
        dest: ~/names.txt  # Replace with the desired path
        content: |
          Dan
          Liz
          Arun
          Brett
    - name: Ensure SELinux is set to enforcing mode
      ansible.builtin.lineinfile:
        path: /root/names.txt
        regexp: '^Liz'
        line: 'Elizabeth'


   
      
    - name: Append a line to change the variable some_variable
      ansible.builtin.lineinfile:
        path: /root/names.txt
        line: "{{last_name}}"
        insertafter: EOF
