name: Ansible test

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  ansible-test:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose a Python version compatible with Ansible
    
    - name: Clone ansible repository
      env:
        SSH_PRIVATE_KEY: ${{ secrets.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 }}
      run: |
        git clone https://$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@github.com/Dan3210/Ansible.git
    
    - name: Access cloned repo
      run: |
        cd Ansible
        ls -la
    
    - name: Install Ansible
      run: |
        pip install ansible
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Run Ansible Playbook
      run: |
        cd Ansible
        ansible-playbook -i inventory test.yml
